import pyautogui
import webbrowser as wb
import time

wb.open("https://web.telegram.org")
time.sleep(30)
for i in range(1):
    pyautogui.press("H")
    pyautogui.press("e")
    pyautogui.press("r")
    pyautogui.press("e")
    pyautogui.press("enter")
    pyautogui.press("I")
    pyautogui.press("enter")
    pyautogui.press("a")
    pyautogui.press("m")
    pyautogui.press("enter")
    pyautogui.press("s")
    pyautogui.press("e")
    pyautogui.press("n")
    pyautogui.press("d")
    pyautogui.press("i")
    pyautogui.press("n")
    pyautogui.press("g")
    pyautogui.press("enter")
    pyautogui.press("u")
    pyautogui.press("enter")
    pyautogui.press("t")
    pyautogui.press("h")
    pyautogui.press("i")
    pyautogui.press("s")
    pyautogui.press("enter")
    pyautogui.press("m")
    pyautogui.press("s")
    pyautogui.press("g")
    pyautogui.press("enter")
    pyautogui.press("u")
    pyautogui.press("s")
    pyautogui.press("i")
    pyautogui.press("n")
    pyautogui.press("g")
    pyautogui.press("enter")
    pyautogui.press("p")
    pyautogui.press("y")
    pyautogui.press("t")
    pyautogui.press("h")
    pyautogui.press("o")
    pyautogui.press("n")
    pyautogui.press(" ")
    pyautogui.press("l")
    pyautogui.press("i")
    pyautogui.press("b")
    pyautogui.press("r")
    pyautogui.press("a")
    pyautogui.press("r")
    pyautogui.press("i")
    pyautogui.press("e")
    pyautogui.press("s")
    pyautogui.press("enter")